config/routes.rb
Rails.application.routes.draw do
  get 'author/index'

  resources :course
  resources :author
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def index
  end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
    def new 
    end

    def index
        @course = Course.all
    end

    def create
        # get all data by create new project
        # and add data to it
        @course = Course.new(article_params)
        # running save command to begin create new course
        if @course.save
            # redirect_to @course
            # params[:course] = @course

            # redirect_to '/course' -- redirect to index page using route name
            # redirect to index page by their [prefix]_path
            redirect_to course_index_path
            # render :index, course:@course
        else
            render 'new'
        end
        # after save data => redirect to another page or success page
        # redirect_to @course
        # redirect to a plain page with information
        # render plain: params[:course].inspect
    end

    def show
        @course = Course.find(params[:id])
    end

    private 
        def article_params
            params.require(:course).permit(:cName, :cDes)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/author/index.html.erb
<p>Đây là trang của author</p>

app/views/course/edit.html.erb
<p>Đây là trang dùng để chỉnh sửa</p>

<%= form_for :course, url:edit_course_path do |f| %>
  <p>
    <%= f.label :title, "Tên khóa học" %><br>
    <%= f.text_field :cName %>
  </p>
 
  <p>
    <%= f.label :text, "Mô tả khóa học" %><br>
    <%= f.text_area :cDes %>
  </p>
 
  <p>
    <%= f.submit "Create new course" %> 
  </p>
<% end %>

app/views/course/index.html.erb
<p>Đây là trang index</p>

<p>Show thông tin những course được add vào</p>

<%= link_to "Add new course", new_course_path %>
<table border="1">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @course.each do |c| %>
    <tr>
      <td><%= c.cName %></td>
      <td><%= c.cDes %></td>
      <td><%= link_to 'Show', course_path(c) %></td>
    </tr>
  <% end %>
</table>

app/views/course/new.html.erb
<p>Đây là trang tạo mới các khóa học</p>

<%= form_for :course, url: course_index_path do |f| %>
  <p>
    <%= f.label :title, "Tên khóa học" %><br>
    <%= f.text_field :cName %>
  </p>
 
  <p>
    <%= f.label :text, "Mô tả khóa học" %><br>
    <%= f.text_area :cDes %>
  </p>
 
  <p>
    <%= f.submit "Create new course" %> 
  </p>
<% end %>

app/views/course/show.html.erb
<p>Show thông tin những course được add vào</p>

<p>Tên khóa học</p>
<%=@course.cName %>

<p>Mô tả khóa học</p>
<%=@course.cDes %>
<br>
<br>
<%= link_to 'Edit', edit_course_path(@course) %>  |   
<a href="/course">Delete</a>
<br>
<br>
<a href="/course">Back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>